// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDKogjnsaFg7ZjharQXCi9IGVDObXcYb4',
    appId: '1:512973562686:web:287bc025dbb5fdf98c426f',
    messagingSenderId: '512973562686',
    projectId: 'capital-taxi-ed8f0',
    authDomain: 'capital-taxi-ed8f0.firebaseapp.com',
    databaseURL: 'https://capital-taxi-ed8f0-default-rtdb.firebaseio.com',
    storageBucket: 'capital-taxi-ed8f0.firebasestorage.app',
    measurementId: 'G-E0L173FQV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk56vt5FPOa-Pas3Ylwjcfka0G5CG8u1s',
    appId: '1:512973562686:android:86a9b963a69d44768c426f',
    messagingSenderId: '512973562686',
    projectId: 'capital-taxi-ed8f0',
    databaseURL: 'https://capital-taxi-ed8f0-default-rtdb.firebaseio.com',
    storageBucket: 'capital-taxi-ed8f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdsY5X_kT5ixIJSx1A4rq5AM4kQP0TDBg',
    appId: '1:512973562686:ios:e4d5a4f4176b4ce18c426f',
    messagingSenderId: '512973562686',
    projectId: 'capital-taxi-ed8f0',
    databaseURL: 'https://capital-taxi-ed8f0-default-rtdb.firebaseio.com',
    storageBucket: 'capital-taxi-ed8f0.firebasestorage.app',
    androidClientId: '512973562686-5do73051i54abmk6vrkf2c9lc6lg7f1q.apps.googleusercontent.com',
    iosClientId: '512973562686-f6or37iqr4ct65ntrclrfbkq176u17el.apps.googleusercontent.com',
    iosBundleId: 'com.example.capitaltaxi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdsY5X_kT5ixIJSx1A4rq5AM4kQP0TDBg',
    appId: '1:512973562686:ios:e4d5a4f4176b4ce18c426f',
    messagingSenderId: '512973562686',
    projectId: 'capital-taxi-ed8f0',
    databaseURL: 'https://capital-taxi-ed8f0-default-rtdb.firebaseio.com',
    storageBucket: 'capital-taxi-ed8f0.firebasestorage.app',
    androidClientId: '512973562686-5do73051i54abmk6vrkf2c9lc6lg7f1q.apps.googleusercontent.com',
    iosClientId: '512973562686-f6or37iqr4ct65ntrclrfbkq176u17el.apps.googleusercontent.com',
    iosBundleId: 'com.example.capitaltaxi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDKogjnsaFg7ZjharQXCi9IGVDObXcYb4',
    appId: '1:512973562686:web:b1fa6d421c9d33238c426f',
    messagingSenderId: '512973562686',
    projectId: 'capital-taxi-ed8f0',
    authDomain: 'capital-taxi-ed8f0.firebaseapp.com',
    databaseURL: 'https://capital-taxi-ed8f0-default-rtdb.firebaseio.com',
    storageBucket: 'capital-taxi-ed8f0.firebasestorage.app',
    measurementId: 'G-WCT28QK3CG',
  );

}